services:

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        node index.js
      "

volumes:
  db-data:
